import { useEffect,useMemo,useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { CalendarClock,CheckCircle2,CircleDollarSign,CreditCard,Loader2,Pause,Play,RefreshCw,ShieldCheck,Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { getNeroxaPlatformAccess, isNeroxaStaff } from "@/features/master/clients/services";
import { canPerform } from "@/features/master/permissions";
import { MasterShell } from "@/features/master/shell/MasterShell";
import { MasterLogin } from "@/features/master/shell/MasterLogin";
import { COMMERCIAL_MODEL_LABELS,SUBSCRIPTION_STATUS_LABELS,type Subscription,type SubscriptionPlan } from "@/features/master/subscriptions/types";
import { loadSubscriptionOverview,updateSubscriptionStatus } from "@/features/master/subscriptions/services";
import { listNeroxaSystems } from "@/features/master/systems/services";
import { listProductPlans,listProducts } from "@/features/master/products/services";

export const Route=createFileRoute("/master-assinaturas")({component:MasterSubscriptionsPage});
const statusTone:Record<keyof typeof SUBSCRIPTION_STATUS_LABELS,string>={PENDING:"bg-blue-50 text-blue-700",ACTIVE:"bg-emerald-50 text-emerald-700",PAUSED:"bg-amber-50 text-amber-700",DELINQUENT:"bg-red-50 text-red-700",CANCELLED:"bg-slate-100 text-slate-500",EXPIRED:"bg-slate-100 text-slate-500"};
const formatCurrency=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);
const formatDate=(value:string|null)=>{if(!value)return "—";const raw=String(value).trim();if(!raw)return "—";const parsed=new Date(/^\d{4}-\d{2}-\d{2}$/.test(raw)?raw+"T12:00:00":raw);return Number.isNaN(parsed.getTime())?"—":new Intl.DateTimeFormat("pt-BR").format(parsed)};

function MasterSubscriptionsPage(){
 const params=typeof window==="undefined"?null:new URLSearchParams(window.location.search);
  const contextClientId=params?.get("clientId") ?? null;
  const contextOrganizationId=params?.get("organizationId") ?? null;
 const [authorized,setAuthorized]=useState<boolean|null>(null),[role,setRole]=useState<import("@/features/master/clients/services").NeroxaPlatformRole|null>(null),[plans,setPlans]=useState<SubscriptionPlan[]>([]),[subscriptions,setSubscriptions]=useState<Subscription[]>([]),[clients,setClients]=useState<{id:string;legal_name:string|null;trade_name:string|null}[]>([]),[systems,setSystems]=useState<{id:string;name:string}[]>([]),[planProducts,setPlanProducts]=useState<Record<string,string[]>>({}),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[saving,setSaving]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const load=async(initial=false)=>{setError(null);if(initial){setLoading(true)}else{setRefreshing(true)}try{const staff=await isNeroxaStaff();setAuthorized(staff);if(!staff)return;const access=await getNeroxaPlatformAccess();setRole(access?.active?access.role:null);const [overview,systemData,productData]=await Promise.all([loadSubscriptionOverview(),listNeroxaSystems(),listProducts()]);setPlans(overview.plans);setSubscriptions(overview.subscriptions);setClients(overview.clients);setSystems(systemData.map(s=>({id:s.id,name:s.name})));const productLinks=await Promise.all(productData.map(async product=>[product.id,await listProductPlans(product.id)] as const));const mapped:Record<string,string[]>={};for(const [productId,links] of productLinks){for(const link of links.filter(item=>item.included)){const plan=overview.plans.find(item=>item.id===link.plan_id);const product=productData.find(item=>item.id===productId);if(plan&&product)mapped[plan.id]=[...(mapped[plan.id]??[]),product.name];}}setPlanProducts(mapped)}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível carregar as assinaturas.")}finally{setLoading(false);setRefreshing(false)}};
 useEffect(()=>{void load(true)},[]);
 const handleStatus=async(id:string,status:"ACTIVE"|"PAUSED"|"CANCELLED")=>{setSaving(id);setError(null);try{await updateSubscriptionStatus(id,status);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível alterar a assinatura.")}finally{setSaving(null)}};
 const scopedSubscriptions=contextOrganizationId?subscriptions.filter(s=>s.client_id===contextOrganizationId):contextClientId?subscriptions.filter(s=>s.client_id===contextClientId):subscriptions;
 const clientMap=useMemo(()=>new Map(clients.map(c=>[c.id,c])),[clients]),planMap=useMemo(()=>new Map(plans.map(p=>[p.id,p])),[plans]);
 const metrics=useMemo(()=>({total:scopedSubscriptions.length,active:scopedSubscriptions.filter(s=>s.status==="ACTIVE").length,pending:scopedSubscriptions.filter(s=>s.status==="PENDING").length,recurring:scopedSubscriptions.filter(s=>["ACTIVE","PAUSED","DELINQUENT"].includes(s.status)).reduce((sum,s)=>sum+s.contracted_recurring_value,0)}),[scopedSubscriptions]);
 if(authorized===false)return <MasterLogin />;
 if(authorized===null||loading)return <main className="grid min-h-screen place-items-center bg-slate-950 text-slate-100"><Loader2 className="h-7 w-7 animate-spin"/></main>;
 return <MasterShell><div className="mx-auto max-w-[1500px] space-y-5 px-4 py-5 sm:px-6">
  <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-400">Gestão · Assinaturas</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-900">Assinaturas</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">Controle planos, valores contratados e recorrência sem antecipar regras do Financeiro.</p></div><Button variant="outline" onClick={()=>void load()} disabled={refreshing}><RefreshCw className={refreshing?"h-4 w-4 animate-spin":"h-4 w-4"}/>Atualizar</Button></section>
  {error&&<Card className="border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</Card>}
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={CreditCard} label="Assinaturas" value={metrics.total.toString()} hint="Total registrado"/><Metric icon={CheckCircle2} label="Ativas" value={metrics.active.toString()} hint="Operações recorrentes"/><Metric icon={CircleDollarSign} label="Recorrência contratada" value={formatCurrency(metrics.recurring)} hint="Base ativa, pausada ou inadimplente"/><Metric icon={CalendarClock} label="Pendentes" value={metrics.pending.toString()} hint="Aguardando ativação"/></div>
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1.25fr)_minmax(360px,.75fr)]"><Card className="border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#102a2e] text-white"><CreditCard className="h-4 w-4"/></div><div><h2 className="text-base font-semibold">Assinaturas recentes</h2><p className="text-xs text-slate-500">Valores congelados no momento da contratação</p></div></div><div className="mt-4 divide-y divide-slate-100">{scopedSubscriptions.slice(0,8).map(s=>{const c=clientMap.get(s.client_id),p=planMap.get(s.plan_id);return <div key={s.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-slate-100 text-slate-600"><Users className="h-4 w-4"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{c?.trade_name||c?.legal_name||"Cliente não identificado"}</p><p className="truncate text-xs text-slate-500">{p?.name||"Plano não identificado"}{p?.system_id ? ` · ${systems.find(system=>system.id===p.system_id)?.name ?? "Segmento"}` : " · Global"} · {COMMERCIAL_MODEL_LABELS[p?.commercial_model ?? "SUBSCRIPTION"]}</p></div><div className="flex items-center justify-between gap-3 sm:justify-end"><div className="text-right"><p className="text-sm font-semibold">{formatCurrency(s.contracted_recurring_value)}</p><p className="text-[11px] text-slate-400">próx. {formatDate(s.next_billing_date)}</p></div><div className="flex items-center gap-2"><span className={"rounded-full px-2.5 py-1 text-[10px] font-medium "+statusTone[s.status]}>{SUBSCRIPTION_STATUS_LABELS[s.status]}</span>{canPerform(role,"manageSubscriptions")&&s.status==="ACTIVE"&&<Button variant="ghost" size="icon" title="Pausar" disabled={saving===s.id} onClick={()=>void handleStatus(s.id,"PAUSED")}><Pause className="h-3.5 w-3.5"/></Button>}{canPerform(role,"manageSubscriptions")&&s.status==="PAUSED"&&<Button variant="ghost" size="icon" title="Reativar" disabled={saving===s.id} onClick={()=>void handleStatus(s.id,"ACTIVE")}><Play className="h-3.5 w-3.5"/></Button>}{canPerform(role,"manageSubscriptions")&&["ACTIVE","PAUSED","PENDING","DELINQUENT"].includes(s.status)&&<Button variant="outline" size="sm" disabled={saving===s.id} onClick={()=>{if(window.confirm("Cancelar esta assinatura? Essa ação altera o status para cancelada."))void handleStatus(s.id,"CANCELLED")}}>Cancelar</Button>}</div></div></div>})}{subscriptions.length===0&&<div className="py-12 text-center"><CreditCard className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-3 text-sm font-medium text-slate-700">Nenhuma assinatura cadastrada</p><p className="mt-1 text-xs text-slate-500">Quando uma assinatura for criada, ela aparecerá aqui.</p></div>}</div></Card>
  <Card className="border-slate-200 bg-[#102a2e] p-5 text-slate-100 shadow-sm"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-400">Catálogo</p><h2 className="mt-2 text-lg font-semibold">Planos Neroxa</h2><p className="mt-2 text-sm leading-6 text-slate-300">O catálogo define referências comerciais. A assinatura guarda o preço efetivamente contratado.</p><div className="mt-5 space-y-2">{plans.slice(0,5).map(p=><div key={p.id} className="rounded-xl border border-white/10 bg-white/5 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{p.name}</p><p className="mt-0.5 text-[11px] text-slate-400">{p.system_id ? systems.find(system=>system.id===p.system_id)?.name ?? "Segmento" : "Plano global"} · {COMMERCIAL_MODEL_LABELS[p.commercial_model]}</p></div><p className="text-sm font-semibold">{p.commercial_model === "PERMANENT" ? formatCurrency(p.base_price) : formatCurrency(p.base_price)}</p></div><div className="mt-2 flex flex-wrap gap-1">{(planProducts[p.id] ?? []).slice(0,5).map(product=><span key={product} className="rounded-full bg-white/10 px-2 py-1 text-[10px] text-slate-300">{product}</span>)}</div></div></div>)}{plans.length===0&&<p className="py-6 text-center text-xs text-slate-400">Nenhum plano cadastrado.</p>}</div><div className="mt-5 flex items-center gap-2 border-t border-white/10 pt-4 text-xs text-slate-400"><ShieldCheck className="h-4 w-4"/>Valores protegidos pela camada de autorização do Master.</div></Card></div>
 </div></MasterShell>;
}
function Metric({icon:Icon,label,value,hint}:{icon:typeof CreditCard;label:string;value:string;hint:string}){return <Card className="border-slate-200 bg-white p-4 shadow-sm"><Icon className="h-4 w-4 text-slate-400"/><p className="mt-3 text-xs font-medium uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></Card>}
