/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterRouteImport } from './routes/master'
import { Route as MasterAssinaturasRouteImport } from './routes/master-assinaturas'
import { Route as MasterClientesRouteImport } from './routes/master-clientes'
import { Route as MasterComercialRouteImport } from './routes/master-comercial'
import { Route as MasterFinanceiroRouteImport } from './routes/master-financeiro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterAssinaturasRoute = MasterAssinaturasRouteImport.update({
  id: '/master-assinaturas',
  path: '/master-assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterClientesRoute = MasterClientesRouteImport.update({
  id: '/master-clientes',
  path: '/master-clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterComercialRoute = MasterComercialRouteImport.update({
  id: '/master-comercial',
  path: '/master-comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterFinanceiroRoute = MasterFinanceiroRouteImport.update({
  id: '/master-financeiro',
  path: '/master-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/master': typeof MasterRoute
  '/master-assinaturas': typeof MasterAssinaturasRoute
  '/master-clientes': typeof MasterClientesRoute
  '/master-comercial': typeof MasterComercialRoute
  '/master-financeiro': typeof MasterFinanceiroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/master': typeof MasterRoute
  '/master-assinaturas': typeof MasterAssinaturasRoute
  '/master-clientes': typeof MasterClientesRoute
  '/master-comercial': typeof MasterComercialRoute
  '/master-financeiro': typeof MasterFinanceiroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/master': typeof MasterRoute
  '/master-assinaturas': typeof MasterAssinaturasRoute
  '/master-clientes': typeof MasterClientesRoute
  '/master-comercial': typeof MasterComercialRoute
  '/master-financeiro': typeof MasterFinanceiroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/master'
    | '/master-assinaturas'
    | '/master-clientes'
    | '/master-comercial'
    | '/master-financeiro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/master'
    | '/master-assinaturas'
    | '/master-clientes'
    | '/master-comercial'
    | '/master-financeiro'
  id:
    | '__root__'
    | '/'
    | '/master'
    | '/master-assinaturas'
    | '/master-clientes'
    | '/master-comercial'
    | '/master-financeiro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MasterRoute: typeof MasterRoute
  MasterAssinaturasRoute: typeof MasterAssinaturasRoute
  MasterClientesRoute: typeof MasterClientesRoute
  MasterComercialRoute: typeof MasterComercialRoute
  MasterFinanceiroRoute: typeof MasterFinanceiroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-assinaturas': {
      id: '/master-assinaturas'
      path: '/master-assinaturas'
      fullPath: '/master-assinaturas'
      preLoaderRoute: typeof MasterAssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-clientes': {
      id: '/master-clientes'
      path: '/master-clientes'
      fullPath: '/master-clientes'
      preLoaderRoute: typeof MasterClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-comercial': {
      id: '/master-comercial'
      path: '/master-comercial'
      fullPath: '/master-comercial'
      preLoaderRoute: typeof MasterComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-financeiro': {
      id: '/master-financeiro'
      path: '/master-financeiro'
      fullPath: '/master-financeiro'
      preLoaderRoute: typeof MasterFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MasterRoute: MasterRoute,
  MasterAssinaturasRoute: MasterAssinaturasRoute,
  MasterClientesRoute: MasterClientesRoute,
  MasterComercialRoute: MasterComercialRoute,
  MasterFinanceiroRoute: MasterFinanceiroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
